---
version: "3"
services:

  web1:
    image: jmalloc/echo-server

  web2:
    image: jmalloc/echo-server

  haproxy:
    image: haproxytech/haproxy-ubuntu:2.0
    volumes:
    - "./haproxy.cfg:/etc/haproxy/haproxy.cfg"
    ports:
    - "80:80"
    depends_on:
    - web1
