---
version: "3"
services:

  web1:
    image: crccheck/hello-world

  web2:
    image: crccheck/hello-world

  static1:
    image: halverneus/static-file-server
    volumes:
    - "./cat.jpg:/web/cat.jpg"

  haproxy:
    image: haproxytech/haproxy-ubuntu:2.0
    volumes:
    - "./haproxy.cfg:/etc/haproxy/haproxy.cfg"
    ports:
    - "80:80"
    - "9000:9000"
    depends_on:
    - web1
    - web2
    - static1
